Repository bank-vaults/vault-operator, pull requests merged in 2023-07, with the labels that each got.

#101 feat: repository standardisation and overhaul
  .github/workflows/ci.yaml
  Dockerfile
  Makefile
  PROJECT
  cmd/main.go
  deploy/charts/vault-operator/crds/crd.yaml
  deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
  deploy/crd/kustomization.yaml
  deploy/crd/kustomizeconfig.yaml
  deploy/crd/patches/cainjection_in_vaults.yaml
  deploy/crd/patches/webhook_in_vaults.yaml
  deploy/default/kustomization.yaml
  deploy/default/manager_auth_proxy_patch.yaml
  deploy/default/manager_config_patch.yaml
  deploy/default/rbac.yaml
  deploy/dev/multi-dc/aws/multi-dc-raft.sh
  deploy/dev/multi-dc/test/multi-dc-raft.sh
  deploy/manager/kustomization.yaml
  deploy/manager/manager.yaml
  deploy/prometheus/kustomization.yaml
  deploy/prometheus/monitor.yaml
  deploy/rbac/auth_proxy_client_clusterrole.yaml
  deploy/rbac/auth_proxy_role.yaml
  deploy/rbac/auth_proxy_role_binding.yaml
  deploy/rbac/auth_proxy_service.yaml
  deploy/rbac/cluster_role_binding.yaml
  deploy/rbac/kustomization.yaml
  deploy/rbac/leader_election_role.yaml
  deploy/rbac/leader_election_role_binding.yaml
  deploy/rbac/role.yaml
  deploy/rbac/role_binding.yaml
  deploy/rbac/service_account.yaml
  deploy/rbac/vault_editor_role.yaml
  deploy/rbac/vault_viewer_role.yaml
  go.mod
  go.sum
  hack/custom-boilerplate.go.txt
  hack/update-codegen.sh
  pkg/apis/addtoscheme_monitor_v1.go
  pkg/apis/addtoscheme_vault_v1alpha1.go
  pkg/apis/vault/v1alpha1/doc.go
  pkg/apis/vault/v1alpha1/embedded_v1.go
  pkg/apis/vault/v1alpha1/groupversion_info.go
  pkg/apis/vault/v1alpha1/vault_types.go
  pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/vault/v1alpha1/fake/fake_vault.go
  pkg/client/clientset/versioned/typed/vault/v1alpha1/vault_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/controller/addtomanager_vault.go
  pkg/controller/vault/suite_test.go
  pkg/controller/vault/vault_controller.go
  test/acceptance_test.go
Labels: enhancement, dependencies

#84 feat: Add configurable AWS KMS encryption context
  deploy/charts/vault-operator/crds/crd.yaml
  deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
  deploy/examples/cr-aws.yaml
  pkg/apis/vault/v1alpha1/vault_types.go
Labels: enhancement

#139 fix: parse docker image references in accordance with the standard grammar
  go.mod
  go.sum
  pkg/apis/vault/v1alpha1/vault_types.go
  pkg/apis/vault/v1alpha1/vault_types_test.go
Labels: bug

#140 build: update golang to the latest version
  Dockerfile
  Makefile
  flake.lock
Labels: dependencies, docker, nix
