Repository bank-vaults/vault-operator, pull requests merged in 2024-02, with the labels that each got.

#365 ci: update dependabot config
  .github/dependabot.yaml
Labels: size/S

#252 fix: make HSM pin an optional argument to allow setting it via the BANK_VAULTS_HSM_PIN env var
  deploy/charts/vault-operator/crds/crd.yaml
  deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
  pkg/apis/vault/v1alpha1/vault_types.go
Labels: size/S

#357 fix: operator throwing panic when storage is empty
  go.mod
  go.sum
  pkg/apis/vault/v1alpha1/vault_types.go
  pkg/controller/vault/vault_controller.go
  pkg/controller/vault/vault_controller_test.go
Labels: size/M

#377 chore: bump go and bank-vaults deps
  .licensei.toml
  go.mod
  go.sum
Labels: size/XL

#380 feat: Cancel previous workflow on push
  .github/workflows/ci.yaml
Labels: size/XS

#367 fix: Use correct label name for ServiceMonitor jobLabel field
  pkg/controller/vault/vault_controller.go
Labels: size/XS

#384 chore: bump versions for charts
  .github/workflows/ci.yaml
  Makefile
  cmd/examples/go.mod
  cmd/examples/go.sum
  deploy/charts/vault-operator/README.md
  deploy/charts/vault-operator/values.yaml
  deploy/dev/microk8s/dev.yaml
  deploy/dev/multi-dc/aws/cr-primary.yaml
  deploy/dev/multi-dc/aws/cr-secondary.yaml
  deploy/dev/multi-dc/aws/cr-tertiary.yaml
  deploy/dev/multi-dc/test/cr-primary.yaml
  deploy/dev/multi-dc/test/cr-secondary.yaml
  deploy/dev/multi-dc/test/cr-tertiary.yaml
  deploy/dev/multi-dc/test/multi-dc-raft.sh
  deploy/examples/cr-alibaba.yaml
  deploy/examples/cr-audit.yaml
  deploy/examples/cr-aws-server-side-encryption.yaml
  deploy/examples/cr-aws.yaml
  deploy/examples/cr-awskms.yaml
  deploy/examples/cr-azure.yaml
  deploy/examples/cr-cert-manager.yaml
  deploy/examples/cr-containers.yaml
  deploy/examples/cr-credentialFromSecret.yaml
  deploy/examples/cr-customports.yaml
  deploy/examples/cr-disabled-root-token-storage.yaml
  deploy/examples/cr-file.yaml
  deploy/examples/cr-gcpkms.yaml
  deploy/examples/cr-gcs-ha-autounseal.yaml
  deploy/examples/cr-gcs-ha.yaml
  deploy/examples/cr-hsm-nitrokey.yaml
  deploy/examples/cr-hsm-softhsm.yaml
  deploy/examples/cr-init-containers.yaml
  deploy/examples/cr-istio.yaml
  deploy/examples/cr-k8s-startup-secret.yaml
  deploy/examples/cr-kvv2.yaml
  deploy/examples/cr-mysql-ha.yaml
  deploy/examples/cr-nodeAffinity.yaml
  deploy/examples/cr-oidc.yaml
  deploy/examples/cr-podAntiAffinity.yaml
  deploy/examples/cr-policy-with-accessor.yaml
  deploy/examples/cr-priority.yaml
  deploy/examples/cr-prometheus.yaml
  deploy/examples/cr-raft-1.yaml
  deploy/examples/cr-raft-ha-storage.yaml
  deploy/examples/cr-raft.yaml
  deploy/examples/cr-resource.yaml
  deploy/examples/cr-statsd.yaml
  deploy/examples/cr-transit-unseal.yaml
  deploy/examples/cr-vault-kv-unseal.yaml
  deploy/examples/cr.yaml
  examples/base/vault.yaml
  examples/kubernetes-auth/README.md
  test/deploy/test-external-secrets-watch-deployment.yaml
Labels: size/XL
