Repository bank-vaults/vault-operator, pull requests merged in 2024-05, with the labels that each got.

#456 ci: update dependabot config
  .github/dependabot.yaml
Labels: size/XS, area/pipeline

#457 feat: Add CRD Support for Oracle Cloud Infrastructure
  Makefile
  deploy/charts/vault-operator/crds/crd.yaml
  deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
  pkg/apis/vault/v1alpha1/vault_types.go
  pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
Labels: size/S, kind/feature

#471 fix: Add a tokenreviews role to the leader-election-role
  deploy/rbac/leader_election_role.yaml
Labels: kind/enhancement, size/S

#470 refactor: remove unused test-files
  deploy/examples/cr-transit-unseal.yaml
  test/acceptance_test.go
  test/deploy/test-configmap-dev.yaml
  test/deploy/test-configmap.yaml
  test/deploy/test-cronjob.yaml
  test/deploy/test-custom-resource.yaml
  test/deploy/test-deploy-ct.yaml
  test/deploy/test-deploy-templating.yaml
  test/deploy/test-deploy-va.yaml
  test/deploy/test-deployment-env-from.yaml
  test/deploy/test-deployment-gcp.yaml
  test/deploy/test-deployment-seccontext.yaml
  test/deploy/test-deployment.yaml
  test/deploy/test-dynamic-env-vars.yaml
  test/deploy/test-secret.yaml
  test/deploy/vault-pipeline-feature.yaml
  test/prometheus.yaml
Labels: kind/design, size/L

#448 chore: bump go version, update nix
  Makefile
  deploy/charts/vault-operator/crds/crd.yaml
  deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
  flake.lock
  flake.nix
  go.mod
  go.sum
  pkg/controller/vault/vault_controller.go
Labels: size/XL, area/dependencies
